### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by evanholt1** [rocknrolla777/mongoose-atlas-search#1]
when i try to use this plugin, it just gives this error when i do a .find( ) query, with the error in the title. i was just trying to use it with the basic provided example, adding just a .connect( ) to connect to a DB. WHY?

`const mongoose = require('mongoose');
const atlasPlugin = require('mongoose-atlas-search');
 
 
const Schema = mongoose.Schema;
 
const UserSchema = new Schema(
  {
    name: String,
    email: String,
    languagel: String,
  },
  {collection: 'movies'}
);
UserSchema.set('validateBeforeSave', false);
 
const UserModel = mongoose.model('User', UserSchema);
 
 
//atlasPlugin.initialize(<options>);
atlasPlugin.initialize({
  model: UserModel,
  overwriteFind: false,
  addFields: {
    id: '$_id'
  },
  searchFunction: query => {
    return {
      'wildcard': {
        'query': `${query}*`,
        'path': '_id',
        'allowAnalyzedField': true
      }
    }
  }
 
});
mongoose.connect("<DB_Connection>").then(async()=>{
  console.log(await UserModel.find().exec());
});`
changing the searchKey value, or removing it. making overwriteFind true or false, didnt help.

**Comment by rocknrolla777** [comment]
Hi! I will check

**Comment by rocknrolla777** [comment]
@evanholt1  Hi there! Thanks for your ticket.

The issue is fixed.  New version is 1.0.5
